#include <sys/ipc.h> 
#include <sys/msg.h> 
#include <sys/types.h> 
#include <stdio.h> 
#include <stdlib.h> 
#include <string.h> 
#include <unistd.h> 
#include <wait.h> 

struct uzenet { 
     long mtype;//ez egy szabadon hasznalhato ertek, pl uzenetek osztalyozasara
     char mtext [100];
	int pont[3]; 
}; 

// sendig a message
int kuld( int uzenetsor ) 
{ 
     const struct uzenet uz = { 5, "Hajra Fradi!",{3,4,5} }; 
     int status; 
     
     status = msgsnd( uzenetsor, &uz, sizeof(struct uzenet) , 0 ); 
	// a 3. param ilyen is lehet: sizeof(uz.mtext)
     	// a 4. parameter gyakran IPC_NOWAIT, ez a 0-val azonos ha
	// van hely az uzenetsorban. Ha nincs hely az uzenetsorban, akkor 
	// 0 eseten varakozik, hogy legyen hely, mig IPC_NOWAIT eseten hibaval
	// visszater
     if ( status < 0 ) 
          perror("msgsnd"); 
     return 0; 
} 
     
// receiving a message. 
int fogad( int uzenetsor ) 
{ 
     struct uzenet uz; 
     int status; 
     	// a negyedik parameter(5) az uzenet azonositoszama
	// ha az 0, akkor a sor elso uzenetet vesszuk ki
	// ha >0 (5), akkor az 5-os uzenetekbol a kovetkezot
	// vesszuk ki a sorbol
	// az 5. parameter (0), IPC_NOWAIT, MSG_EXCEPT, MSG_NOERROR lehet
	// ha nincs uzenet msgrcv var, kiveve ha IPC_NOWAIT definialt
	// ha MSG_EXCEPT definialt akkor a megadott uzenet azonositotol
	// eltero (nem 5) elso uzenetet olvassa be
	// ha MSG_NOERROR adott akkor a nagyobb meretu uzenet csonkitott valtozatat
	// olvassa be 
     status = msgrcv(uzenetsor, &uz,sizeof(struct uzenet), 5, 0 ); 
     
     if ( status < 0 ) 
          perror("msgsnd"); 
     else
          printf( "A kapott uzenet kodja: %ld, szovege:  %s\n", uz.mtype, uz.mtext );
	printf("A pont adatok: %d,%d,%d\n",uz.pont[0],uz.pont[1],uz.pont[2]); 
     return 0; 
} 

int main (int argc, char* argv[]) { 
     pid_t child; 
     int uzenetsor, status; 
     // key_t kulcs; 
     
     // msgget needs a key, generated by ftok 
     // msgget first param (key) may equal to IPC_PRIVATE 
     //kulcs = ftok(argv[0],1); 
     //printf ("A kulcs: %d\n",kulcs);
     uzenetsor = msgget( IPC_PRIVATE, 0600 | IPC_CREAT ); 
     if ( uzenetsor < 0 ) { 
          perror("msgget"); 
          return 1; 
     } 
     
     child = fork(); 
     if ( child > 0 ) { 
          kuld( uzenetsor );  // Parent sends a message. 
	  sleep(1); // ha ez nincs a fogad be is olvassa!!!!
          fogad(uzenetsor);
	  wait( NULL ); 
          // After terminating child process, the message queue is deleted. 
          status = msgctl( uzenetsor, IPC_RMID, NULL ); 
          if ( status < 0 ) 
               perror("msgctl"); 
          return 0; 
     } else if ( child == 0 ) { 
          fogad( uzenetsor );
	struct uzenet valasz;
	strcpy(valasz.mtext,"Pont tavolsag.");
	valasz.mtype=5; //valasz.mtext="Pont tavolsag:";
	valasz.pont[0]=15;
	msgsnd(uzenetsor,&valasz,sizeof(struct uzenet),0);
	return 0; 
          // The child process receives a message. 
     } else { 
          perror("fork"); 
          return 1; 
     } 
     
     return 0; 
} 
