#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>  //fork
#include <sys/wait.h> //waitpid
#include <errno.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <sys/time.h>
#include <unistd.h>
#include <mqueue.h>
#include <stdlib.h>
#include <ctype.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <fcntl.h>
#include <time.h>
#include <sched.h>
#include <signal.h>
#include <bits/siginfo.h>
#include <signal.h>
#include <sys/types.h>
void handler(int signumber)
{
    printf("Signal with number %i has arrived\n",signumber);
}
void player1()
{
//    pause();

}
void checker()
{
    kill(getppid(),SIGTERM);
}
int main()
{
    int status;
    int n;
int r;
int r2;
    signal(SIGTERM,handler);
int num;
    int fd[0];
    pipe(fd);
   	pid_t  child=fork(); //forks make a copy of variables
if (child<0)
{
    perror("The fork calling was not succesful\n");
    exit(1);
}
if (child>0) //the parent process, it can see the returning value of fork - the child variable!
{
   player1();
        if((close(fd[0])) == -1){
          perror("close:");}
      int k;
                int r=rand()%100+1;
	printf("The random number generated of the parent is  %d\n",r);
         write(fd[0], &r, sizeof(r));
      
    int disp;
read(fd[0], &disp, sizeof(disp));
printf("number read from child  is  %d\n",disp);
close(fd[0]);
waitpid(child,&status,0); //wait(&status)
//String toSend;
	if(r==disp){
	printf("you guessed right");
	}else if(r<disp){
	printf("guess higher");
	}else{
	printf("guess lower");
	}
	//write(fd[0], toSend, toSend.length()+1);

	



    

}else
{
    //1st child process
    checker();
    int i,k;
srand(time(NULL));
int r2=rand()%100+1;
	printf("The random number generated by the second player is  %d\n",r2);
     if((close(fd[0])) == -1){
          perror("close:");}

        write(fd[1],&r2,sizeof(r2)); 
	//	sleep(1);    
     close(fd[0]);

}
return 0;
}
