#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <errno.h>
#include <time.h>

int main(){

	int status;
	int r,i;
		
	pid_t process=fork();
	srand(getpid());

		for(i=0; i<5; i++){
						
			if(process==0){
				r=rand()%10;
				printf("Number generated by the child process: \n");
				printf("%d \n", r);	
			}
	
			else{ 
				wait(&status);
				r=rand()%10;
				printf("Number generated by the parent process: \n");
				printf("%d \n", r);	
			}
		}

	return 0;

}
